// Module included in the following assemblies:
// assembly-about-common.adoc

[id="con-what-is-prod-common_{context}"]

= What is {ProductNameShort}?

{ProductNameStartSentence}, also known as {ProductNameShort}, is an inspection and reporting tool. It is designed to find, identify, and report environment data, or facts, such as the number of physical and virtual systems on a network, their operating systems, and other configuration data. In addition, it is designed to find, identify, and report more detailed facts for some versions of key {CompanyName} packages and products for the IT resources in that network.

The ability to inspect the software and systems that are running on your network improves your ability to understand and report on your entitlement usage. Ultimately, this inspection and reporting process is part of the larger system administration task of managing your inventories.

{ProductNameStartSentence} requires the configuration of two basic structures to access IT resources and run the inspection process. A _credential_ contains user access data, such as the user name and password or SSH key of a user with sufficient authority to run the inspection process on a particular source or some of the assets on that source. A _source_ contains data about a single asset or multiple assets that are to be inspected. These assets can be physical machines, virtual machines, or containers, identified as host names, IP addresses, IP ranges, or subnets. These assets can also be a systems management solution such as {vCenterServerName} or {SatelliteServerName}. You can save multiple credentials and sources to use with {ProductNameShort} in various combinations as you run inspection processes, or _scans_. When you have completed a scan, you can access these facts in the output as a collection of formatted data, or _report_, to review the results.

By default, the credentials and sources that are created when using {ProductNameShort} are encrypted in a database. The values are encrypted with AES-256 encryption. They are decrypted when the {ProductNameShort} server runs a scan with the use of a vault password to access the encrypted values that are stored in the database.

{ProductNameStartSentence} is an agentless inspection tool, so there is no need to install the tool on every source that is to be inspected. However, the system that {ProductNameShort} is installed on must have access to the systems to be discovered and inspected.

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.

// Topics from AsciiDoc conversion that were used as source for this topic:
//
//
