// Module included in the following assemblies:
// assembly-about-common.adoc

[id="con-right-for-me-common_{context}"]

= Is {ProductNameShort} right for me?

{ProductNameStartSentence} is intended to help you find and understand your {CompanyName} product inventory, including unknown product usage across complex networks. The reports generated by {ProductNameShort} are best understood through your partnership with a {CompanyName} Solution Architect (SA) or Technical Account Manager (TAM) or through the analysis and assistance supplied by the Subscription Education and Awareness Program (SEAP). Pilot programs that are currently underway include {ProductNameShort} as one tool that can help integrate your software inventory with other new and established {CompanyName} management offerings.

ifdef::discovery_install_guide[]
Although you can install and use {ProductNameShort} independently and then generate and view report data, the {ProductNameShort} documentation does not provide any information to help you interpret report results. In addition, although {CompanyName} Support can provide some basic assistance related to installation and usage of the {ProductNameMedium} tool, the support team does not provide any assistance to help you understand the reports. The graduated pilot programs are designed for subsets of {CompanyName} customers who qualify based on their {CompanyName} product profile and other factors. These pilot programs are helping to refine the ingestion, rendering, analysis, and usage of report information as part of a management solution to help you understand your product inventory across your environments, whether on-premise, cloud, or containers.
endif::discovery_install_guide[]

ifdef::qpc_install_guide[]
As an upstream project, {ProductNameShort} is not formally supported by {CompanyName}. However, there are certain customer scenarios and configurations where use of the upstream tool for scanning your environments and reporting your inventory is an ideal solution. If you are engaged with your SA, TAM, or a member of the SEAP team and have been instructed to use {ProductNameShort} as your inventory scanning tool, you will be supported by those groups as you install and use {ProductNameShort}.
endif::qpc_install_guide[]

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.

// Topics from AsciiDoc conversion that were used as source for this topic:
// con-working-with-scans.adoc
// con-qpc-scan-works.adoc
// con-scans-and-scan-jobs.adoc (inspected but redundant with other info)
// con-working-scan-jobs.adoc (inspected but redundant with other info)
