// Module included in the following assemblies:
// assembly-adding-sat-sources-creds-gui.adoc

[id="proc-adding-sat-sources-gui-{context}"]

= Adding satellite sources

You can add sources from the initial Welcome page or from the Sources view.

// .Prerequisites

// Any prereqs?

.Procedure

. Click the option to add a new credential based on your location:
  * From the Welcome page, click *Add Source*.
  * From the Sources view, click *Add*.

+
The Add Source wizard opens.

. On the Type page, select *Satellite* as the source type and click *Next*.

. On the Credentials page, enter the following information.
.. In the *Name* field, enter a descriptive name.
.. In the *IP Address or Hostname* field, enter the IP address or host name of the Satellite server for this source. Enter a different port if you do not want a scan for this source to run on the default port 443. For example, if the IP address of the Satellite server is 192.0.2.15 and you want to change the port to 80, you would enter `192.0.2.15:80`.
// NOTE: 80 is just a guess...
.. In the *Credentials* list, select the credential that is required to access the Satellite server for this source. If a required credential does not exist, click the *Add a credential* icon to open the Add Credential wizard.
.. In the *Connection* list, select the SSL protocol to be used for a secure connection during a scan of this source. Select *Disable SSL* to disable secure communication during a scan of this source.
.. If you need to upgrade the SSL validation for the Satellite server to check for a verified SSL certificate from a certificate authority, select the *Verify SSL Certificate* check box.
. Click *Save* to save the source and then click *Close* to close the Add Source wizard.

// .Verification steps
// (Optional) Provide the user with verification method(s) for the procedure, such as expected output or commands that can be used to check for success or failure.

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
