// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

[id="proc-merging-reports-gui-{context}"]

= Merging reports

From the Scans view, you can select two or more reports and merge them into a single report.

There might be several reasons that you would choose to merge reports, including the following examples:

* You might have a large IT infrastructure with many different administrators, each of whom can access and scan only a part of that infrastructure.
* You might run multiple separate scans to limit the demand on CPU resources of the machines that are being scanned, especially in situations where deep scanning is required.
* You might want to run scans on a single type of source, isolating your network, satellite, and vcenter data into separate reports for your own internal purposes and then merge these reports later.

For these and similar reasons, it is possible that you will run multiple scans to provide complete scan coverage of your entire IT infrastructure. Merging reports enables you to combine the data from multiple scans into a single report.

.Prerequisites

To merge reports, you must select at least two scans for which the most recent scan jobs have completed successfully.

.Procedure

. From the Scans view, select the check box for one or more scans.
. Click *Merge reports*. A confirmation dialog box shows the selected scans.
. Click *Merge* to merge the scans into a single report and download the merged reports.

.Verification steps

// the report_id____ID___DATE_TIME_.tar.gz string renders correctly in preview
// do not change underscore coding
The merged report is saved to the downloads location for your browser as a [filename]`.tar.gz` file, for example, [filename]`report_id_110_20190529_095005.tar.gz`. The file name format is [filename]`report_id____ID___DATE_TIME_.tar.gz`, where `_ID_` is the unique report ID assigned by the server, `_DATE_` is the date in _yyyymmdd_ format, and `_TIME_` is the time in the _hhmmss_ format, based on the 24-hour system. The date and time data is determined by the interaction of the browser that is running the client with the server APIs.

// the report_id______ID_ string renders correctly in preview
// do not change underscore coding
To view the reports, uncompress the [filename]`.tar.gz` file into a [filename]`report_id______ID_` directory. The uncompressed report bundle includes four report files, two details reports in CSV and JSON formats, and two deployments reports in CSV and JSON formats.

While you can view and use the output of these reports for your own internal processes, their format is designed for use by the {CompanyName} Subscription Education and Awareness Program (SEAP) team during customer engagements and for other {CompanyName} internal processes.

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
