// Module included in the following assemblies:
// assembly-installing-scripted-online-inst.adoc

[id="proc-transferring-packages-offline-inst_{context}"]

= Transferring the packages to the offline machine

After you download the {ProductNameShort} server and CLI packages and build the PostgreSQL database container image, you must transfer them to the offline machine where {ProductNameShort} will be installed.

// .Prerequisites

// Before you begin, review the prerequisites for {ProductNameShort}.

.Procedure

. Create a `packages` directory on the disconnected machine to use for the package transfer, where `_lib_ is the library version, either `lib` or `lib64`, and `_version.release.patch_` is the complete version number of the {ProductInstallerToolName} RPM package. Use the following command:
+
[source,options="nowrap"]
----
# mkdir -p /usr/_lib_/qpc-tools-_version.release.patch_/install/packages
----

// path...path to the offline machine? double-check that this has all the steps needed if two physical machines are involved.
. Move the downloaded packages from the connected machine into the `packages` directory on the disconnected machine, where `_pathtopackages_` is the path to the `packages` directory. Use the following command:
+
[source,options="nowrap"]
----
# mv /_pathtopackages_/usr/_lib_/qpc-tools-_version.release.patch_/install/packages
----

// .Verification steps
// (Optional) Provide the user with verification method(s) for the procedure, such as expected output or commands that can be used to check for success or failure.

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
