// Module included in the following assemblies:
// assembly-installing-scripted-offline-inst.adoc

[id="proc-downloading-tools-package-inst_{context}"]

= Downloading the {ProductToolsName} package

The {ProductToolsName} package contains tools to install and maintain {ProductNameShort}.

// .Prerequisites

// Before you begin, review the prerequisites for {ProductNameShort}.

// NOTE: This topic currently qpc only, discovery tools are enabled, not downloaded.

.Procedure

. From a browser session on the connected machine, go to the following link for information about the {ProductToolsName} package and for the link to download the latest version: {QPCcommandOfflineDownloadToolsPackageLandingGeneric}[{QPCcommandOfflineDownloadToolsPackageLandingGeneric}^].

. To download the {ProductToolsName} package, click the following package download link that applies to your operating system:
.. For {RHELNameShort} 8 and {CentOSName} 8, click *{QPCcommandOfflineDownloadToolsPackageNameRHEL8}*.
.. For {RHELNameShort} 7 and {CentOSName} 7, click *{QPCcommandOfflineDownloadToolsPackageNameRHEL7}*.
.. For {RHELNameShort} 6 and {CentOSName} 6, click *{QPCcommandOfflineDownloadToolsPackageNameRHEL6}*.

// .Verification steps
// (Optional) Provide the user with verification method(s) for the procedure, such as expected output or commands that can be used to check for success or failure.

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
