// Module included in the following assemblies:
// assembly-installing-scripted-offline-inst.adoc

[id="proc-installing-scripted-offline-qpc-inst_{context}"]

= Installing with the offline installation process

During the {ProductNameShort} installation process, you enter commands to install the server and the command line interface (CLI).

The following information includes commands for the default installation process. However, you can change some of the defaults used by the installation process by setting options that are defined in xref:ref-tools-install-options-inst_assembly-installing-scripted-offline-inst-ctxt[Options for the {ProductToolsName} install command].

// .Prerequisites

// . ...

.Procedure

To install {ProductNameShort}, you install three packages, the {ProductToolsName} package, the {ProductNameShort} server package, and the {ProductNameShort} CLI package. Use the following steps:

== Installing {ProductToolsName}

Install {ProductToolsName}.

ifdef::qpc_install_guide[]
. Run the following command, where `_/path_` is the full path to the location on the disconnected machine where you transferred the packages.
+
[source,options="nowrap",subs="+quotes"]
----
# rpm -Uvh --force`_/path_`
----
endif::qpc_install_guide[]

== Installing the server

Install the server. The default server installation process prompts you to supply a password for the {ProductNameShort} server administrator and a password for the {PostgreSQLName} database user.
[IMPORTANT]
====
As a best practice, note the {ProductNameShort} server administrator and the {PostgreSQLName} database user passwords in the password management system that is used by your organization. {ProductNameStartSentence} does not offer a method to recover these passwords.

In addition, if you later use {ProductToolsName} to upgrade {ProductNameShort}, you must use the same database user name and password during the upgrade. The failure to use the same database credentials could result in data loss.
====

ifdef::discovery_install_guide[]
. Install the server by entering the following command:
+
[source,options="nowrap",subs="+quotes"]
----
# dsc-tools server install
----

. Enter a password for the {ProductNameShort} server administrator.

. Enter a password for the {PostgreSQLName} database user.

. Enter your username for the {ContainerCatalogName}, also known as the `registry.redhat.io` image registry website.

. Enter your password for the {ContainerCatalogName}.
endif::discovery_install_guide[]

ifdef::qpc_install_guide[]
. Install the server by entering the following command, where `_/path_` is the full path to the location on the disconnected machine where you transferred the packages and `_version.release.patch_` is the version of the {ProductNameShort} server package:
+
[source,options="nowrap",subs="+quotes"]
----
# qpc-tools server install --offline-files=`_/path_` --version=`_version.release.patch_`
----

. Enter a value for the {ProductNameShort} server administrator password.

. Enter a value for the {PostgreSQLName} database password.
endif::qpc_install_guide[]

== Installing the command line interface

Install the command line interface.

ifdef::discovery_install_guide[]
. Install the command line interface by entering the following command, where `_/path_` is the full path to the location on the disconnected machine where you transferred the packages:
+
[source,options="nowrap",subs="+quotes"]
----
# dsc-tools cli install --offline-files=`_/path_`
----
endif::discovery_install_guide[]

ifdef::qpc_install_guide[]
. Install the command line interface by entering the following command, where `_/path_` is the full path to the location on the disconnected machine where you transferred the packages:
+
[source,options="nowrap",subs="+quotes"]
----
# qpc-tools cli install --offline-files=`_/path_`
----
endif::qpc_install_guide[]


.Verification steps

. For a successful installation of the packages, the output appears similar to the following example:
+
----
Installation complete.
----

// ....link to a topic that contains the description about the default config when running this simple install?

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.

// Topics from AsciiDoc conversion that were used as source for this topic:
// ....
