// Module included in the following assemblies:
// assembly-installing-scripted-online-inst.adoc

[id="proc-installing-scripted-online-inst_{context}"]

= Installing with the online installation process

During the {ProductNameShort} installation process, you enter commands to install the server and the command line interface (CLI). The simplest method for installing {ProductNameShort} is to run the online installation with all of the default options. With this method, the install process prompts you to do the following actions:
ifdef::discovery_install_guide[]

* Enter your user name and password for the {ContainerCatalogName}.
endif::discovery_install_guide[]
* Set a password for the {ProductNameShort} server administrator.
* Set a password for the database user.


The following information includes commands for the default installation process. However, you can change some of the defaults used by the installation process by setting options that are defined in xref:ref-tools-install-options-inst_assembly-installing-scripted-online-inst-ctxt[Options for the {ProductToolsName} install command].

// .Prerequisites

// * Download the {ProductNameShort} installer. For more information, see (...link to download inst topic...).

.Procedure

To install the {ProductNameShort} server and CLI packages, use the following steps:

== Installing the server



ifdef::discovery_install_guide[]
Install the server. The default server installation process prompts you to enter your user name and password for the {ContainerCatalogName} (the registry.redhat.io website). It also prompts you to supply a password for the {ProductNameShort} server administrator and a password for the {PostgreSQLName} database user.
endif::discovery_install_guide[]

ifdef::qpc_install_guide[]
Install the server. The default server installation process prompts you to supply a password for the {ProductNameShort} server administrator and a password for the {PostgreSQLName} database user. 
endif::qpc_install_guide[]
[IMPORTANT]
====
As a best practice, note the {ProductNameShort} server administrator and the {PostgreSQLName} database user passwords in the password management system that is used by your organization. {ProductNameStartSentence} does not offer a method to recover these passwords.

In addition, if you later use {ProductToolsName} to upgrade {ProductNameShort}, you must use the same database user name and password during the upgrade. The failure to use the same database credentials could result in data loss.
====

ifdef::discovery_install_guide[]
. Install the server by entering the following command:
+
[source,options="nowrap",subs="attributes,+quotes"]
----
# dsc-tools server install
----

. At the prompt, enter your user name for the {ContainerCatalogName}, also known as the registry.redhat.io image registry website.

. At the prompt, enter your password for the {ContainerCatalogName}.

. At the prompt, set a password for the {ProductNameShort} server administrator.

. At the prompt, set a password for the {PostgreSQLName} database user.
endif::discovery_install_guide[]

ifdef::qpc_install_guide[]
. Install the server by entering the following command:
+
[source,options="nowrap",subs="+quotes"]
----
# qpc-tools server install
----

. At the prompt, set a password for the {ProductNameShort} server administrator.

. At the prompt, set a password for the {PostgreSQLName} database user.
endif::qpc_install_guide[]

.Verification steps

. For a successful installation of the server package, the output appears similar to the following example:
+
----
Installation of the server was successful.
----

== Installing the command line interface

Install the command line interface.

The recommended method is to include the options to set the port and IP address of the {ProductNameShort} server. These options must be set so that the {ProductNameShort} command line interface can communicate with the server.

ifdef::discovery_install_guide[]
. Install the command line interface by entering the following command, where `server_port` is the port that the {ProductNameShort} server is using for communication and `_server_host_` is the IP address of the server:
+
[source,options="nowrap",subs="+quotes"]
----
# dsc-tools cli install --server-port=_server_port_ --server-host=_server_host_
----
endif::discovery_install_guide[]

ifdef::qpc_install_guide[]
. Install the command line interface by entering the following command, where `server_port` is the port that the {ProductNameShort} server is using for HTTPS communication and `_server_host_` is the IP address of the server:
+
[source,options="nowrap",subs="+quotes"]
----
# qpc-tools cli install --server-port=_server_port_ --server-host=_server_host_
----
endif::qpc_install_guide[]

.Verification steps

. For a successful installation command line interface packages the output appears similar to the following example:
+
----
Installation of the CLI was successful.
----

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.

// Topics from AsciiDoc conversion that were used as source for this topic:
// ....
