// Module included in the following assemblies:
// assembly-installing-scripted-online-inst.adoc

[id="proc-transferring-packages-offline-inst_{context}"]

= Transferring the packages to the offline machine

After you download the {ProductNameShort} server and CLI packages and build the PostgreSQL database container image, you must transfer them to the offline machine where {ProductNameShort} will be installed.

// .Prerequisites

// Before you begin, review the prerequisites for {ProductNameShort}.

.Procedure

. Create a directory on the disconnected machine to use for the package transfer. During the steps to install the server and command line interface, you enter the path to this directory as part of the commands.

. Move the following packages from the connected machine into the directory that you just created on the disconnected machine:
+
* The {ProductToolsName} package that applies to your operating system version, qpc-tools.el8.noarch.rpm, qpc-tools.el7.noarch.rpm, or qpc-tools.el6.noarch.rpm.
* The {ProductNameShort} server package `quipucords_server_image.tar.gz`.
* The database container image `postgres.9.6.10.tar`.
* The {ProductNameShort} command line interface package that applies to your operating system version, `qpc.el6.noarch.rpm`, `qpc.el7.noarch.rpm`, or `qpc.el8.noarch.rpm`.

// .Verification steps
// (Optional) Provide the user with verification method(s) for the procedure, such as expected output or commands that can be used to check for success or failure.

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
