// Module included in the following assemblies:
// assembly-installing-scripted-online-inst.adoc
// assembly-installing-scripted-offline-inst.adoc

[id="ref-tools-install-options-inst_{context}"]

= Options for the {ProductToolsName} install command

The installation procedures in this guide install the {ProductNameShort} server and CLI packages with all of the default options. However, the `install` subcommand that installs the {ProductNameShort} server and command line interface packages includes options to customize the installation process.

The following information lists the `install` subcommand options, along with applicable usage information and default values, for the server and CLI packages.

== Server installation options

`--offline-files=_offline_files_path`:: Sets the fully qualified path to the files on the disconnected machine, for example, the transferred server and command line interface packages, that are needed to complete an offline installation. This option has no default value and is used only when specified during an offline installation.

`--version=_version.patch.release_`:: Enables the installation of a specific {ProductNameShort} server version. Contains the semantic versioning format (version.release.patch, such as 0.9.0) of the {ProductNameShort} server that you want to install. Required if the `offline-files` option is specified. This option has a default of the latest version.

`--home-dir=_server_home_dir_`:: Sets the fully qualified path to the installation directory for the {ProductNameShort} server. Defaults to `~/{ProductInCommands}/`.

`--port=_server_port_`:: Sets the port number for the {ProductNameShort} server. Defaults to `9443`.

`--open-port=true|false`:: Determines whether to open the port in the firewall during the installation. This option enables communication between the {ProductNameShort} server and any remote clients over the port defined in the `port` option. Contains a true or false value. Defaults to true. Supply `false` to install without opening the server port in the firewall. The installation script must run with elevated privileges to open the server port.

ifdef::discovery_install_guide[]
`--registry-user=_registry_website_username_`:: Specifies your user name for the {ContainerCatalogName}, also known as the `registry.redhat.io` image registry website. You are prompted for this value during server installation.

`--registry-password=_registry_website_password_`:: Specifies your password for the {ContainerCatalogName}, also known as the `registry.redhat.io` image registry website. You are prompted for this value during server installation.

endif::discovery_install_guide[]

`--db-user=_database_username_`:: Sets the database user name for PostgreSQL. Defaults to `postgres`.

`--db-password=_database_password_`:: Sets the database user password for PostgreSQL. This option has no default value. If omitted, {ProductToolsName} prompts for a password.

`--username=_server_username_`:: Sets the {ProductNameShort} server administrator user name. Defaults to `admin`.

`--password=_server_password_`:: Sets the {ProductNameShort} server administrator password. This option has no default value. If omitted, {ProductToolsName} prompts for a password.



== Command line interface installation options

`--offline-files=_offline_files_path_`:: Sets the fully qualified path to the files on the disconnected machine, for example, the transferred server and command line interface packages, that are needed to complete an offline installation. This option has no default value and is used only when specified during an offline installation.

`--version=_version.patch.release_`:: Enables the installation of a specific {ProductNameShort} CLI version. Contains the semantic versioning format (version.release.patch, such as 0.9.0) of the {ProductNameShort} CLI that you want to install. Required if the `offline-files` option is specified. This option has a default of the latest version.

`--home-dir=_cli_home_dir_`:: Sets the fully qualified path to the installation directory for the {ProductNameShort} CLI. Defaults to `~/{ProductInCommands}/`.

`--server-host=_server_IP_address_`:: Sets the IP address to use to connect to the {ProductNameShort} server. This option has no default value. You must either set a value during the CLI package installation or set a value by configuring the server connection for the command line interface.

`--server-port=_server_port_`:: Sets the port number to use to connect to the {ProductNameShort} server. This option has no default value. You must either set a value during the CLI package installation or set a value by configuring the server connection for the command line interface.



// Topics from AsciiDoc conversion that were used as source for this topic:
// ...
