// Module included in the following assemblies:
// assembly-installing-prerequisites-inst.adoc
// ...

[id="ref-env-prerequsites-inst_{context}"]

= Other environment prerequisites

The environment in which you are going to use {ProductNameShort} must meet the following requirements. Some of these requirements affect the systems on which you are going to run {ProductNameShort}. Others affect the systems in your IT infrastructure that you are going to scan with {ProductNameShort}.

On the machine where {ProductNameShort} is installed:

* If you install the {ProductNameShort} server and CLI packages on different machines, {ProductToolsName} must be installed on both machines to run each installation.
* If you install the {ProductNameShort} server and CLI packages on different machines, the CLI machine must be able to connect to the server machine.
* The {ProductNameShort} server must have access to the IT infrastructure assets that are to be scanned.
// ifdef::discovery_install_guide[]
// * If you plan to use {ProductNameShort} as part of the pilot of Unified Subscriptions Inventory and Reporting (USIR) in conjunction with Cloud Management Services for RHEL.... server machine must be able to connect to the Internet (must have internet connectivity?) to send reports to the upload service.
// endif::discovery_install_guide[]


On the systems where {ProductNameShort} runs scans:

* Any network sources that are targeted for scanning must be running the Secure Shell (SSH) protocol.
* A user account that is used as a credential for a scan requires the `bash` shell. The shell cannot be the `/sbin/nologin` shell or the `/bin/false` shell.
* A user account that is used as a credential for a network scan must have adequate permissions to run commands and read certain files on those systems. For example, some commands that run during a scan require privilege elevation to gather the complete set of facts for the scan. The _{UserGuide}_ guide has additional information about the creation of credentials for network scans and the privileges that must be associated with those credentials to enable a more complete scan of network assets.
* A user account that is used as a credential for a network scan where authentication is done with an SSH key must have a copy of the private key on the {ProductNameShort} server. The private key must be stored in the `~/{ProductInCommands}/server/volumes/sshkeys` directory, the default location for this directory at the time of server installation. 





// Topics from AsciiDoc conversion that were used as source for this topic:
// ...
