// Module included in the following assemblies:
// assembly-installing-prerequisites-inst.adoc
// ...

[id="ref-sw-prerequsites-inst_{context}"]

= Software prerequisites

The system on which you are going to install {ProductNameShort} must have the following software requirements installed:

* *Operating system:* The latest release of the following operating system versions:
ifdef::discovery_install_guide[]
** {RHELName} 8
endif::discovery_install_guide[]
ifdef::qpc_install_guide[]
** {RHELName} 6, 7, or 8
** {CentOSName} 6 or 7
+
[NOTE]
====
{RHELNameShort} 7 or 8 or {CentOSName} 7 are the recommended operating system versions. For {RHELNameShort} 6 or {CentOSName} 6, the minimum required kernel is 2.6.32-431 or later.
====
endif::qpc_install_guide[]

In addition to these software requirements, {ProductNameShort} has dependencies on other software. However, in some cases these dependencies are installed for you during installation, or instructions for their installation is integrated as part of the {ProductNameShort} installation process. The process to install dependencies can vary according several factors, including your operating system and whether you are doing an offline or online installation. Therefore, install the dependencies only as instructed by the {ProductNameShort} installation steps.

The {ProductNameShort} dependencies include the following software:

* Ansible 2.4 or later, depending on the requirements of your operating system.
ifdef::discovery_install_guide[]
* {PodmanName} container software.
endif::discovery_install_guide[]
ifdef::qpc_install_guide[]
* Container software, either {PodmanName} or {DockerName}, depending on the requirements of your operating system.
endif::qpc_install_guide[]
* The PostgreSQL database.
* {PythonName}, 3.4 or 3.6, depending on the requirements of your operating system.

// Topics from AsciiDoc conversion that were used as source for this topic:
// ...
