[id='con-cli-connection']

== Configuring the qpc command line tool connection

After the Quipucords server is running, you can configure the qpc command line tool to work with the server. When the command line tool is configured, you can log in to Quipucords with the command line interface and begin setting up and running scans on your IT infrastructure.

The '+qpc server config+' command configures the connection between the qpc command line tool and the Quipucords server.

The '+qpc server config+' command takes the following options:
* The '+--host+' option is required. If you are using the qpc command line interface on the same system where the server is running, you can supply the loopback address '+127.0.0.1+' as the value. Otherwise, supply the IP address for your Quipucords server.
* The '+--port+' option is optional. The default value for this option is '+9443+'. If you decided to remap the Quipucords default exposed server port to another port, the port option is required. You must supply the port option and the remapped value in the command, for example, '+--port 8443+'.