[id='con-creds-sources']

== Working with Credentials and Sources

The type of source that you are going to inspect determines the type of data that is required for credential and source configuration. Quipucords currently supports the following source types in the source creation command:

* network

* vcenter

* satellite

A network source is composed of one or more host names, one or more IP addresses, IP ranges, or a combination of these network resources. A vcenter, for vCenter Server, or satellite, for Satellite, source is created with the IP address or host name of that system management solution server.

In addition, the source creation command references one or more credentials. Typically, a network source might include multiple credentials because it is expected that many credentials would be needed to access a broad IP range. Conversely, a vcenter or satellite source would typically use a single credential to access a particular system management solution server.

The following scenarios provide examples of how you would create a network, vcenter, or satellite source and create the credentials required for each.