[id='con-connect-server-cli']

If you chose to complete the step-by-step installation, you must configure a connection between the :product-title: server and the command line tool from each machine where you plan to use the command line interface. If you chose the scripted install, one connection to the server is configured for you on the same machine where the server is installed, but you must configure any additional connections, for example, on a machine that is remote from the server machine.

After you configure the connection between the server and the command line tool, you can use the command line interface to connect to the :product_title: server. After you are logged in, you can begin using :product-title: to set up and run scans on your IT infrastructure.

For example, if you are configuring the command line tool on the same system as the server and the server uses the default exposed server port, you would enter the following command to configure the :product-title_cmd: command line tool:

----
# :product-title_cmd: server config --host 127.0.0.1
----

However, if you are configuring the command line tool on a system that is remote from the server, the :product-title: server is running on the IP address 192.0.2.0, and the port is remapped to 8443, you would enter the following command to configure the :product-title_cmd: command line tool:

----
# :product-title_cmd: server config --host 192.0.2.0 --port 8443
----
