[id='proc-viewing-scan-report']

== Viewing the Scan Report

When the scan job completes, you have the capability to produce a report for that scan job. You can request a report with all the details, or facts, of the scan, or request a deployments report. The deployments report process runs steps to merge the facts found during the inspection of the various hosts that are contacted during the scan. When possible, the report process also runs steps to deduplicate redundant systems. For both types of reports, you can produce the report in JavaScript Object Notation (JSON) format or comma-separated values (CSV) format.

.Procedure

To generate a deployments report, enter the '+qpc report deployments+' command and specify the identifier for the scan job and the format for the output file.

For example, if you want to create the deployments report for a scan with the scan job identifier of 1 and you want to generate that report in CSV format in the '+~/scan_result.csv+' file, you would enter the following command:

----
# qpc report deployments --scan-job 1 --csv --output-file=~/scan_result.csv
----

However, if you want to create the detailed report, you would use the '+qpc report details+' command. This command takes the same options as the '+qpc report deployments+' command. The output is not deduplicated and merged, so it contains all facts from each source. For example, to create the detailed report for a scan with the scan job identifier 1, with CSV output in the '+~/scan_result.csv+' file, you would enter the following command:

----
# qpc report details --scan-job 1 --csv --output-file=~/scan_result.csv
----