[id="configuring-system-purpose_{context}"]


= Configuring system purpose using Anaconda



[NOTE]

====

While it is strongly recommended that you configure System Purpose, it is an optional feature of the {productname} {productnumber} installation program.
You can select the *Not Specified* option if you do not want to configure System Purpose. If you want to enable System Purpose after the installation completes, you can do so using the [command]`syspurpose` Kickstart command.

====



.Procedure



. From the *Installation Summary* window, click *System Purpose*.



. Select the required system role from the *Role* pane.



. Select the required service level agreement from the *Red Hat Service Level Agreement* pane.



. Select the required usage from the *Usage* pane.



. Click btn:[Done] to apply the settings and return to the *Installation Summary* window.



The System Purpose data is now available for Subscription Manager to auto-attach to the system.
See System Manager documentation for further System Purpose information.



//TODO: Need information from Anni on Subscription Manager.




= Configuring System Purpose using Kickstart



Use the [command]'syspurpose' command to configure System Purpose in a Kickstart configuration file.



The following actions are available

:

role::


Set the intended role of the system. This action uses the following format:

+

[subs="quotes"]

----

syspurpose --role=
----

+

====



The role assigned can be:



* [option]'Desktop'

* [option]'Server'

* [option]'Workstation'

* [option]'Computenode'


* [option]'Not Specified'



====

sla::



Set the intended sla of the system. This action uses the following format:

+
[subs="quotes"]

----

syspurpose --sla=
----

+

====



The sla assigned can be:



* [option]'Premium'


* [option]'Standard'

* [option]'Self Support'

* [option]'Not Specified'



====

usage::



Set the intended usage of the system. This action uses the following format:


+
[subs="quotes"]


----

syspurpose --usage=

----

+

====

The usage assigned can be:

* [option]`Production`
* [option]`Disaster Recovery`


* [option]`Not Specified`



====

addon::



Set additional layered products or features. To add multiple items specify [command]`--addon` multiple times, once per layered product/feature:

+
[subs="quotes"]

----

syspurpose --addon=

----

= Configuring System Purpose using the syspurpose command line tool




You can use the syspurpose command line tool to make changes to the system purpose after installation. The syspurpose command line tool is not the same as the [option]'syspurpose' command in Kickstart. These tools are similar but use different syntax.

[NOTE]
====
Using the syspurpose command line tool to set role, sla, and usage will influence the subscriptions that are auto-attached to the system.  If your system is already registered and has subscriptions attached that do not satisfy the system purpose that you desire, then you can run [option]'subscription-manager remove --all' attached subscriptions, use syspurpose to set the desired purposes, and run [option]'subscription-manager attach --auto' to re-entitle the system based on the newly set system purpose attributes.


.Table

[options="System Purpose Command Settings"]

|====
|Command Option |Description



|set-role <ROLE>

|Set the role for the system.



|unset-role

|Clear the role currently on the system. The system returns to an unset state.



|set-sla <SLA>
|Sets the service level agreement for the system.

|unset-sla
|Clear the service level agreement on the system. The system returns to an unset state.

|syspurpose set-usage <USAGE>
|Sets the usage for the system. You can use values like [option]'production' or [option]'qa'.

|unset-usage
|Clear the usage for the system. The system returns to an unset state.

|show
|Shows all the values currently set for the system including any addons.

.Example
[options="Setting the service level agreement using the syspurpose command line tool"]

----
# syspurpose set-sla premium
service_level_agreement set to premium
System purpose successfully sent to the subscription management server.
----

.Example
[options="Showing system purpose settings using the syspurpose command line tool"]

----
# root@localhost syspurpose show
  {
   "addons": [
     ""
  ],
  "role": "desktop".
  "service_level_agreement": "premium"
  }
System purpose syccessfully sent to the subscription management server.
----

//TODO: Add Additional Resources

//[discrete]

//= Additional resources

//* Reference to Composer content.

//* Reference to Subscription Manager.
