[id='proc-install-docker-centos6-rhel6']

== Installing Docker on Red Hat Enterprise Linux and CentOS 6.6 or later using yum

.Procedure
. Make sure that you are logged in as a user with sudo or root privileges.

. Download the Docker RPM package to the current directory:
+
----
# curl -k -O -sSL https://yum.dockerproject.org/repo/main/centos/6/Packages/docker-engine-1.7.1-1.el6.x86_64.rpm
----

. Install the required packages:
+
----
# sudo yum install -y yum-utils device-mapper-persistent-data lvm2 libcgroup xz
----

. Install the Docker package with yum:
+
----
# sudo yum localinstall --nogpgcheck docker-engine-1.7.1-1.el6.x86_64.rpm
Starting Docker on Red Hat Enterprise Linux and CentOS 6.6 or later
----

. After you install Docker, you must start it and verify that it is running. Start the Docker daemon:
+
----
# sudo service docker start
----

. Verify that Docker is installed correctly. To do this step, run the hello-world image:
+
----
# sudo docker run hello-world
----

. This command displays output similar to the following truncated example. The first section of the output contains a message about the installation status:
+
----
Unable to find image 'hello-world:latest' locally
latest: Pulling from hello-world
a8219747be10: Pull complete
91c95931e552: Already exists
hello-world:latest: The image you are pulling has been verified. Important: image verification is a tech preview feature and should not be relied on to provide security.
Digest: sha256:aa03e5d0d5553b4c3473e89c8619cf79df368babd18681cf5daeb82aab55838d
Status: Downloaded newer image for hello-world:latest
Hello from Docker.
This message shows that your installation appears to be working correctly.

...
----

. To ensure that Docker starts when you start your system, enter the following command:
+
----
# sudo chkconfig docker on
----

After you complete the steps to install Docker for Red Hat Enterprise Linux 6.6 or later or CentOS 6.6 or later, you can continue with the Quipucords server installation steps in Installing the Quipucords Server Container Image.