[id='proc-merging-scan-results']

== Merging Scan Results

You can combine results from two or more scan jobs, reports, or JSON details report files and use that merged data to create a single report. You can start this process by using the '+qpc report merge+' command.

.Procedure

For example, if you want to merge the results from the scan jobs with identifiers of '+11+', '+15+', and '+22+', you would enter the following command:

----
# qpc report merge --job-ids 11 15 22
----

If you want to merge the results from reports with identifiers of '+1+', '+2+', and '+3+', you would enter the following command:

----
# qpc report merge --report-ids 1 2 3
----

Additionally, if you would like to create a merged report from JSON details report files, you would enter the following command:

----
# qpc report merge --json-files /path/to/file1.JSON /path/to/file2.JSON
----

You may also specify a directory with many JSON details reports with the following command:

----
# qpc report merge --json-directory /path/to/directory_with_json
----

The above command run an asynchronous job. The output of the above commands provides a job id that can be used to check the status of the merge job. To check the status of a merge job, run the following command:

----
# qpc report merge-status --job 1
----

The output of the above command provides a report identifier that can be used to access the merged data. You can use this identifier and the '+qpc report+' command with the '+details+' or '+deployments+' subcommands to generate a report from the merged results.