// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

[id="proc-merging-reports-gui-{context}"]

= Merging reports

From the Scans view, you can select two or more reports and merge them into a single report.

// move some of these ideas to an assembly topic...
There might be several reasons that you would chose to merge reports. For example, you might have a large IT infrastructure with many different administrators, each of whom can access and scan only a part of that infrastructure. Alternatively, you might run multiple separate scans to limit the demand on CPU resources of the machines that are being scanned, especially in situations where deep scanning is required. Lastly, you might want to run scans on a single type of source, isolating your network, satellite, and vcenter data into separate reports for your own internal purposes.

For these and similar reasons, it is likely that you will run multiple scans to provide complete scan coverage of your entire IT infrastructure. Merging reports enables you to combine the data from multiple scans into a single report.

.Prerequisites

To merge reports, you must select at least two scans for which the most recent scan jobs have completed successfully.

.Procedure

. From the Scans view, select the check box for one or more scans.
. Click btn:[Merge reports]. A confirmation dialog box shows the selected scans.
. Click btn:[Merge] to merge the scans into a single report and download the merged reports.

.Verification steps

// My older browsers require renaming the file ("download" for Chrome, random string for FF) so that it has a .tar.gz extension on the end.
// Otherwise (at least in my RHEL 7) the file type is not recognized and Archive Manager can't decompress it.
// David C. opened an issue for Ryan to investigate--issue 52.
TBD

// .Additional resources
// * A bulleted list of links to other material closely related to the contents of the procedure module.
// * Currently, modules cannot include xrefs, so you cannot include links to other content in your collection. If you need to link to another assembly, add the xref to the assembly that includes this module.
