[id='ref-qpc-requirements']

== :product-title: requirements

Before installing :product-title: in your environment, review the following guidelines about installing and running :product-title::

* You must install :product-title: on a system that is running Red Hat Enterprise Linux 6 or 7, CentOS 7, or Fedora 27 or 28.
** For an installation on Fedora, the scripted installation of :product-title: might not work correctly on all systems. Therefore, the best practice for a Fedora installation is to use the step-by-step installation instructions.
* The system that :product-title: is installed on must have access to the systems to be discovered and inspected.
* Any network sources that are targeted for the inspection process must be running SSH.
* For a scan of network systems, the user account (credential) that :product-title: uses for the SSH connection into the target systems must have adequate permissions to run commands and read certain files on those systems. For example, some of the commands require privilege elevation to gather the complete set of facts for the scan. For more information about these commands, see Commands Used in Scans of Remote Network Assets
* The credential user account requires a '+bash+' shell. For example, the shell cannot be the '+/sbin/nologin+' or '+/bin/false+' shell.
* :product-title: server requires a Postgres 9.6.10 database (this will be installed for scripted installations).
* The command line interface requires python 3.4+.

== Hardware Requirements
* *CPU:* 2 core minimum with a recommended 4 cores.
* *Disk:* Storage: 30 GB
* *RAM:* 1 GB minimum with a recommended 2 GB.
