[id='con-deduplication-sys']

== Dedupplication of Systems

Quipucords uses specific facts about a system to identify duplicate systems. The following phases use these specific facts to remove duplicate systems during the deduplication process:

* All systems from Network sources are combined into a single network system set. Systems are considered to be duplicates if they have the same value for the '+subscription_manager_id+' or '+bios_uuid+' facts.

* All systems from vCenter sources are combined into a single vcenter system set. Systems are considered to be duplicates if they have the same value for the '+vm_uuid+' fact.

* All systems from Satellite sources are combined into a single satellite system set. Systems are considered to be duplicates if they have the same value for the '+subscription_manager_id+' fact.

* The Network system set is merged with the Satellite system set to form a single network-satellite system set. Systems are considered to be duplicates if they have the same value for the '+subscription_manager+' fact or matching MAC address values in the '+mac_addresses+' fact.

* The Network-Satellite system set is merged with the vCenter system set to form the complete system set. Systems are considered to be duplicates if they have matching MAC address values in the '+mac_addresses+' fact or if the vcenter value for the '+vm_uuid+' fact matches the network value for the '+bios_uuid+' fact.