[id='con-fingerprints-process']

== Fingerprints and the Fingerprinting Process

The Quipucords scan process is used to discover the systems in your IT infrastructure and to inspect and gather information about the nature and contents of those systems. A system is any entity that can be interrogated by the Quipucords inspection tasks through an SSH connection, vCenter Server data, or the Satellite API. Therefore, a system can be a machine, such as a physical or virtual machine, and it can also be a different type of entity, such as a container.

During a scan, information, or a collection of facts, about a system is gathered from a single source (such as a network source only) or multiple sources (such as a network source and satellite source). A fact is a single piece of data about a system. Facts are processed to create a summarized set of data for that system that is called a fingerprint. A fingerprint is a set of facts that identifies a unique system and the features on that system, such as the operating system, CPU architecture, number of CPUs and cores, the different products that are installed on that system, the entitlements that are in use on that system, and so on.

Fingerprinting data is generated when you run a scan job. The results are held in the database until you request a deployments report for a scan. If you request a detailed report, you receive the raw facts for that scan without any fingerprinting. When you request a deployments report, you receive the fingerprinting data that includes the results from the deduplication, merging, and post-processing processes. These processes include identifying installed products and versions from the raw facts, finding consumed entitlements, finding and merging duplicate instances of products from different sources, and finding products installed in nondefault locations, among other steps.

The following sections show example fingerprint data, describe the components of a fingerprint, and describe in more detail the process that is used to create the fingerprint.