[id='con-scan-job-lifecycle']

== Scan Job Life Cycle

An individual instance of a scan, or _scan job_, moves through several states during its lifecycle.

When you start a scan, a scan job is created and the scan job is in the _created_ The scan job is then queued for processing and the scan job transitions to the _pending_ state. Due to the lightweight nature of the Quipucords server, scan jobs run serially.

As the Quipucords server reaches a specific scan job in the queue, that scan job transitions from the _pending_ state to the _running_ state as the processing of that scan job begins. If the scan process completes successfully, the scan job transitions to the _completed_ state and the scan job produces results that can be viewed in a report. If the scan process results in a fatal error that prevents successful completion of the scan, the scan job halts and the scan job transitions to the _failed_ state. An additional status message for the failed scan contains information to help determine the cause of the failure.

Other states for a scan job result from user action that is taken on the scan job. You can pause or cancel a scan job while it is pending or running. A scan job in the paused state can be restarted. A scan job in the _canceled_ state cannot be restarted.