[id='proc-pausing-restart-scan']

== Pausing and Restarting a Scan

As you use Quipucords, you might need to stop a currently running scan. There might be various business reasons that require you to do this, for example, the need to do an emergency fix due to an alert from your IT health monitoring system or the need to run a higher priority scan if a lower priority scan is currently running.

When you stop a scan by using the '+scan pause+' command, you can restart that same scan by using the '+scan restart+' command. To pause and restart a scan, use the following steps:

.Procedure

. Make sure that you have the scan job identifier for the currently running scan. For more information about obtaining the scan job identifier, see Showing Scan Job Status.

. Enter the command to pause the scan job. For example, if the scan job identifier is '+1+', you would enter the following command:
+
----
# qpc scan pause --id 1
----

. When you are ready to start the scan job again, enter the command to restart the scan. For example, to restart scan '+1+' you would enter the following command:
+
----
# qpc scan restart --id 1
----
