[id='proc-cleaning-the-db']

== Cleaning out the Database

Our command to run a postgres container does implement docker volumes. Volumes allow our postgres data to be persistent, which means that the data will remain even if the postgres container is removed and recreated. If for any reason you would like to delete your postgres database, you will need to remove the docker volume.

Removing the volume for RHEL 6 or Centos 6

# rm -rf /var/lib/docker/volumes/qpc-data

Removing the volume for RHEL 7, Centos 7, Fedora 27, or Fedora 28

# docker volume rm qpc-data

[id='proc-adding-cli-backslash']

== Adding CLI Inputs with Backslashes

A single backslash is used as an escape character in both Shell and Python, which can cause undesired values if only one backslash is present. Therefore, CLI inputs containing a backslash will need to be escaped with another backslash \\. For example if you wanted to add a credential with the username '+Domain\Username+', the value would have to be escaped:

----
# qpc cred add --type vcenter --name ActiveDirectory --username Domain\\Username --password
----