// This assembly is included in the following assemblies:
// ...

ifdef::context[:parent-context: {context}]

[id="assembly-install-scripted-online-qpc_{context}"]

:context: assembly-install-scripted-online-qpc-ctxt

= Installing....scripted...online....qpc

{ProductNameStartSentence} is delivered in two parts, a command line tool as an RPM package and a server as container images.

The automated installation runs an installer that uses Ansible to install the command line tool, the server image, and the database image. When you run the automated installation, the server is installed and started as described in (....link to the default config description topic from Configuring and Starting Quipucords...). However, you can change some of the defaults used by the automated installation with the (....link to Installation Options topic....).

.Prerequisites

For more information about {ProductNameShort} prerequisites, see (...link to prereqs topic....).

.Procedure

TEXT To ...do install...do these interesting things....

// do you need level offset in each assembly? at master doc level only? confused about this one.

include::modules/proc-install-scripted-online-qpc.adoc[leveloffset=+1]


// .Related Information
// * Bulleted list of links to concepts, reference, or other tasks closely related to this user story.
// * Include only the most relevant items as links, not every possible related item.
// * Delete section title and bullets if no related information is needed.

// Topics from AsciiDoc conversion that were used as source for this topic:
// ....

// Restore the context to what it was before this assembly.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
