// This assembly is included in the following assemblies:
//

ifdef::context[:parent-context: {context}]

[id="assembly-adding-sources-creds-gui-main"]

:context: assembly-adding-sources-creds-gui-main-ctxt

= Adding sources and credentials

To prepare {ProductNameShort} to run scans, you must add the parts of your IT infrastructure that you want to scan as one or more sources. You must also add the authentication information, such as a username and password or SSH key, that is required to access those sources as one or more credentials. Because of differing configuration requirements, you add sources and credentials according to the type of source that you are going to scan.

// .Prerequisites
// * (keeping here temporarily, but probably not using this section in this topic)
// * Sentence or a bulleted list of pre-requisites that must be in place or done before the user starts this task.
// * Delete section title and bullets if the task has no required pre-requisites.
// * Text can be a link to a pre-requisite task that the user must do before starting this task.

.Learn more

As part of the general process of adding sources and credentials that encompass the different parts of your IT infrastructure, you might need to complete a number of tasks.

Add network sources and credentials to scan assets such as physical machines, virtual machines, or containers in your network. To learn more, see the following information:

* xref:assembly-adding-net-sources-creds-gui[Adding network sources and credentials]

Add satellite sources and credentials to scan your deployment of {SatelliteServerName} to find the assets that it manages. To learn more, see the following information:

* xref:assembly-adding-sat-sources-creds-gui[Adding satellite sources and credentials]

Add vcenter sources and credentials to scan your deployment of {vCenterServerName} to find the assets that it manages. To learn more, see the following information:

* xref:assembly-adding-vcent-sources-creds-gui[Adding vcenter sources and credentials]

// do you need level offset in each assembly? at master doc level only? confused about this one.

include::assembly-adding-net-sources-creds-gui.adoc[leveloffset=+1]

include::assembly-adding-sat-sources-creds-gui.adoc[leveloffset=+1]

include::assembly-adding-vcent-sources-creds-gui.adoc[leveloffset=+1]

// .Related Information
// * Bulleted list of links to concepts, reference, or other tasks closely related to this user story.
// * Include only the most relevant items as links, not every possible related item.
// * Delete section title and bullets if no related information is needed.

// Restore the context to what it was before this assembly.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
