// This assembly is included in the following assemblies:
// assembly-merging-downloading-reports-gui-main.adoc

ifdef::context[:parent-context: {context}]

[id="assembly-merging-reports-gui"]

:context: assembly-merging-reports-gui-ctxt

= Merging reports

If you choose to divide the scanning tasks for your IT infrastructure into several discrete scans, you can merge the output of those scans into a single report.

Merged reports are also downloaded at the time of merging so that you can view the data that was gathered and processed during that scan. Reports for a scan are available in two formats, a comma-separated variable (CSV) format and a JavaScript Object Notation (JSON) format. They are also available in two content types, raw output from the scan as a details report and processed content as a deployments report.

// .Prerequisites
// * Sentence or a bulleted list of pre-requisites that must be in place or done before the user starts this task.
// * Delete section title and bullets if the task has no required pre-requisites.
// * Text can be a link to a pre-requisite task that the user must do before starting this task.

.Learn more

To learn more about merging reports and downloading the merged reports, see the following information:

* xref:proc-merging-reports-gui_{context}[Merging reports]

To learn more about how reports are created, see the following information. This information includes a chronology of the processes that change the raw facts of a details report into fingerprint data, and then change fingerprint data into the deduplicated and merged data of a deployments report. This information also includes a partial fingerprint example to show the types of data that are used to create a {ProductNameShort} report.

* xref:con-how-reports-created-gui_assembly-merging-reports-gui-ctxt[How reports are created]
* xref:ref-fingerprint-example-gui_assembly-merging-reports-gui-ctxt[A fingerprint example]

// do you need level offset in each assembly? at master doc level only? confused about this one.

include::modules/proc-merging-reports-gui.adoc[leveloffset=+1]

:context: assembly-merging-reports-gui-ctxt
include::modules/con-how-reports-created-gui.adoc[leveloffset=+1]

:context: assembly-merging-reports-gui-ctxt
include::modules/ref-fingerprint-example-gui.adoc[leveloffset=+2]


// .Related Information
// * Bulleted list of links to concepts, reference, or other tasks closely related to this user story.
// * Include only the most relevant items as links, not every possible related item.
// * Delete section title and bullets if no related information is needed.

// Restore the context to what it was before this assembly.
ifdef::parent-context[:context: {parent-context}]
ifndef::parent-context[:!context:]
